### ISSUE TITLE
Container element for lighthouse report should be more specific

### ISSUE THREAD

**Issue by calvinnwq** [blencorp/react-lighthouse-viewer#1]
https://github.com/blencorp/react-lighthouse-viewer/blob/b2152ad167e9785d1b54424e5cabff6b292d5b96/src/index.js#L44

This selector assumes that there are no other `<main>` elements on the page. If there is, especially one that is high up in the DOM tree, then it breaks.

**Comment by naodya** [comment]
@calvinnwq, thanks for pointing that out. On it.

**Comment by naodya** [comment]
@calvinnwq, `<main>` now has a unique class. Closing issue.
