### ISSUE TITLE
Error and nothing render if using react-lighthouse-viewer@1.0.9, after getting issue in react-lighthouse-viewer@2.7.0

### ISSUE THREAD

**Issue by vaibbhav** [blencorp/react-lighthouse-viewer#10]
![Screenshot from 2020-04-14 16-56-56](https://user-images.githubusercontent.com/11900196/79220104-0942d300-7e71-11ea-95b1-28083fb69b71.png)

**Comment by naodya** [comment]
Fixed on latest version. checkout #9 for details.
