### ISSUE TITLE
Report not rendering.....

### ISSUE THREAD

**Issue by vaibbhav** [blencorp/react-lighthouse-viewer#11]
Thanks for the 2.8 release. 
Report not rendering when I'm using  ` <ReportViewer json={JSONREPORTMOB} />`  two times on the same page one for desktop report and other for mobile report.  
 `<ReportViewer id="mobile" />` must accept custom id as props or auto-generate id,

From below code I'm getting report of `{JSONREPORTMOB}` in first tab `<ReportViewer json={JSONREPORTDESK} />`
**Note: Im not getting error in console but template id is same for both report **  `<ReportViewer />`
Find code below: 

`<TabContent activeTab={this.state.activeTab}>
  <TabPane tabId="1">
    <Card>
        <CardBody>
            <ReportViewer json={JSONREPORTDESK} />
        </CardBody>
      </Card>
  </TabPane>
  <TabPane tabId="2">
    <Card>
        <CardBody>
            <ReportViewer json={JSONREPORTMOB} />
        </CardBody>
    </Card>
  </TabPane>
</TabContent>`

![Background](https://user-images.githubusercontent.com/11900196/79350083-a460a900-7f54-11ea-981c-cbe52358d0b1.png)
![Screenshot from 2020-04-15 19-45-51](https://user-images.githubusercontent.com/11900196/79350093-a75b9980-7f54-11ea-9441-77c5c9397e83.png)

**Comment by vaibbhav** [comment]
Any Update ?

**Comment by naodya** [comment]
@vaibbhav starting version `6.0.1` you can dynamically pass `id` for your components.

e.g.

```jsx
function App() {
 ...
  return (
    <>
      <div className="report-wrapper">
        <ReportViewer id="report-one" json={jsonReport} />
      </div>
      <div className="report-wrapper">
        <ReportViewer id="report-two" json={jsonReport} />
      </div>
    </>
  );
}
```

**Comment by naodya** [comment]
Fixed
