### ISSUE TITLE
Update to LH 6.0

### ISSUE THREAD

**Issue by paulirish** [blencorp/react-lighthouse-viewer#12]
lh6 is out. its report renderer supports lh 5 (and 4) json just fine.  though it has a few new things supported too.

;)

https://github.com/GoogleChrome/lighthouse/releases/tag/v6.0.0

**Comment by spacedawwwg** [comment]
You're everywhere @paulirish ! 😂 

+1 for lh6 update please!

**Comment by MUTOgen** [comment]
@paulirish Is it ok to pass new JSON from lh6? Any issues?

**Comment by naodya** [comment]
`react-lighthouse-viewer@6.0.0` adds support for Lighthouse 6 reports.
