### ISSUE TITLE
Dynamic JSON report

### ISSUE THREAD

**Issue by testevez** [blencorp/react-lighthouse-viewer#13]
Is there a way to use fetch to load in a JSON report instead of import, so that the JSON report  can be dynamic?

This is a general  question, I just added some code that I am using below to share a bit.

Thanks!!

`import React from 'react';
import { render } from 'react-dom';
import ReportViewer from '../../../src/index.js';
import jsonReport from "../../../example/src/report5.json";
import { Component } from 'react';

//console.log(drupalSettings.pfizer_lighthouse);

/**
 * App
 */
class App extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            report: null,
            loaded: false,
        };
    }

    /**
     * Load articles via Drupal JSON:API.
     */
    componentDidMount() {

        fetch('/sites/default/files/lighthouse-reports/pfpfizeruscom-stage.pfizersite.io-20200512T112713.json?sdasds')
            .then(data => this.setState({ report: data, loaded: true }));
    }

    render() {

        const { report, loaded } = this.state;

        if (!loaded) {
            return <p>Loading ...</p>;
        }
        if (report.length === 0) {
            return <p>No results</p>;
        }

        console.log(report);

        return <ReportViewer json={report} />;

    }
}

export default App;
`

**Comment by testevez** [comment]
The console.log of the  report from fetch looks identical  to the  console.log of the imported report, so I think the issue is that  I  am not using the  component  as intended.

**Comment by naodya** [comment]
@testevez it is possible to do it like so

```JSX
import React from "react";

import ReportViewer from "react-lighthouse-viewer";
import "./App.css";

function App() {
  const [loading, setLoading] = React.useState(true);
  const [jsonReport, setJsonReport] = React.useState({});

  React.useEffect(() => {
    const loadData = async () => {
      let response = await fetch(
        `http://blencorp.com/react-lighthouse-viewer/report6.json`
      );
      response = await response.json();

      setJsonReport(response);
      setLoading(false);
    };

    loadData();
  }, []);
  return (
    <div className="App">
      <header className="App-header">
        {loading ? (
          <div>Loading report data...</div>
        ) : (
          <ReportViewer json={jsonReport} />
        )}
      </header>
    </div>
  );
}

export default App;

```

**Comment by samos123** [comment]
It's working fine for me as well. You might have to convert the json string into json. See for example how I did it here: https://github.com/websu-io/websu-ui/blob/master/src/Home.js#L14

**Comment by naodya** [comment]
Works
