### ISSUE TITLE
Lighthouse 5

### ISSUE THREAD

**Issue by TAnas0** [blencorp/react-lighthouse-viewer#2]
Hello there,

I am trying to use your component with a JSON report generated using the latest version of lighthouse (version 5).

I tried setting it up in different ways, but I am facing issues with the rendering and an error message.

I was wondering, if you are supporting Lighthouse 5? If not, are you planning to do so? And if not also, what would be the steps to support Lighthouse 5, since they had some breaking changes?
I am seriously interested in supporting Lighthouse 5 as a feature.

The error states:
```
TypeError: " is not a valid URL."
```
![Screenshot from 2019-08-05 09-08-31](https://user-images.githubusercontent.com/12121506/62449183-915cce80-b761-11e9-9ff1-12e8f5a6014d.png)

I tried going through the source looking for that error message, or the mounted hook that React complains about, but couldn't find anything.

I would appreciate any clarification you could bring and thanks in advance

**Comment by rytikovroman1994** [comment]
Most likely it is a mistake because of the node version. The fifth version of the beacon works with 10 nodes.

**Comment by naodya** [comment]
@TAnas0 next major version will support Lighthouse 5. Pull requests are always welcome :)

**Comment by TAnas0** [comment]
@naody I submitted a pull request to support Lighthouse 5 and seems working fine: https://github.com/blencorp/react-lighthouse-viewer/pull/4

I found your codebase to be clean and simple. If you want, I can be of more help to you.

Are you interested in adding features such as this [plugin](https://github.com/GoogleChrome/lighthouse-stack-packs)? This is another feature that I have on my radar, and I might need it soon.

Let me know, and if yes please create an issue for it.

Cheers

**Comment by naodya** [comment]
@TAnas0, thanks for the pull request, it's now merged. This react  package needs some cleanup work, it does not directly use the lighthouse npm package as a dependency, rather uses code copied out of the package. This makes it a bit hard whenever lighthouse gets an update. I'll try to improve this in upcoming versions. I also like your idea of plugins, please feel free to drop some examples and we can incorporate it. 

Cheers!!
