### ISSUE TITLE
Publishing without styles?

### ISSUE THREAD

**Issue by j-mendez** [blencorp/react-lighthouse-viewer#30]
Thank you for the work done on the repo. I was trying to figure out how the source code and package dist have some differences. In the source theres a css file thats being loaded but, in the dist its removed and inlined with the template. I tried using `yarn transpile` to see if it would properly build the dist but, it looks like some things where mainly stitched together? Trying to make a fork with some small changes for use with next.js.

**Comment by j-mendez** [comment]
In the index.js theres an style import on `npm run transpile` it imports the file. On the versions that are public for `react-lighthouse-viewer` there is no style import. Reason being your package works in `nextjs` but, when trying to fork and make adjustments it looks like it was stitched together manually so that it cannot be truly re-used. Having to go through the differences to see what the changes are and this is misleading of it being open-source since this is code that is coming from a different location. @naodya @TAnas0.
 
![Screen Shot 2022-05-14 at 8 31 09 AM](https://user-images.githubusercontent.com/8095978/168425828-a2ce6479-b3f3-4b6a-afe3-1a7b49831c7c.png)
i

**Comment by naodya** [comment]
@j-mendez , you are right, most of the pieces of this package are stitched. My plan is to fix everything with the next major release.

**Comment by j-mendez** [comment]
@naodya Thanks for the feedback. On that note, going to close the issue.
