### ISSUE TITLE
CSS is broken

### ISSUE THREAD

**Issue by sanjay22nava** [blencorp/react-lighthouse-viewer#5]
The component is loading. but, CSS is broken. does it require a CSS loader?

![image](https://user-images.githubusercontent.com/54605355/71312662-56e78b80-23fb-11ea-9de5-1314583f5e66.png)

![image](https://user-images.githubusercontent.com/54605355/71312687-aa59d980-23fb-11ea-8ab1-bbd58cccc9e7.png)

**Comment by naodya** [comment]
@sanjay22nava , I'm unable to replicate this issue. Can you please provide the steps?

**Comment by sanjay22nava** [comment]
@naody  I just installed the package react-lighthouse-viewer as shown in the example with [create-react-app](https://github.com/facebook/create-react-app)

here is [repo](https://github.com/sanjay22nava/react-lighthouse) with index.js in the app.

```
import React from "react";
import ReactDOM from "react-dom";
import ReportViewer from "react-lighthouse-viewer";
import jsonReport from "./report.json";

const App = () => <ReportViewer json={jsonReport} />;

ReactDOM.render(<App />, document.getElementById("root"));

```

This is just boilerplate create-react-app, no other package except react-lighthouse-viewer.

**Comment by victorcarvalhosp** [comment]
same issue here on version 2.0. 

Using version 1.0.9 it's working with just a small glitch where the First Meaningful Paint, First CPU Idle, Max Potential First Input Delay results and the images are not appearing.
![image](https://user-images.githubusercontent.com/4266657/72211630-5e0b3200-34ad-11ea-9add-dcd74d0705fc.png)

**Comment by ivanjeremic** [comment]
Same issue here any fixes?

**Comment by firassziedan** [comment]
pull request #7 fix this issue

**Comment by naodya** [comment]
Fixed on latest version. checkout #9 for details.
