### ISSUE TITLE
CSS Broken , module not working

### ISSUE THREAD

**Issue by vaibbhav** [blencorp/react-lighthouse-viewer#9]
Error on front-end and console:

Failed to compile...
./node_modules/react-lighthouse-viewer/dist/report-styles.css (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-lighthouse-viewer/dist/report-styles.css)
Unclosed bracket (754:19)

  752 |   flex-grow: 0;
  753 |   flex-shrink: 0;
> 754 |   flex-basis: calc(3 * var(--report-font-size);
      |                   ^
  755 | }
  756 | 
  757 |

Fix : remove the below line from css :
file: react-lighthouse-viewer/dist/report-styles.css

initial code : 
.lh-audit--load-opportunity .lh-audit__display-text {
  text-align: right;
  flex: 0 0 calc(3 * var(--report-font-size));
}

final code to update: 

.lh-audit--load-opportunity .lh-audit__display-text {
  text-align: right;
  flex: calc(3 * var(--report-font-size));
}

**Comment by vaibbhav** [comment]
FIle: client/node_modules/react-lighthouse-viewer/example/dist/main.css

#error line : 759 
Initial code : 

#fix: .lh-audit--load-opportunity .lh-audit__display-text {
  text-align: right;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: calc(3 * var(--report-font-size);
}

final code to update:

.lh-audit--load-opportunity .lh-audit__display-text {
  text-align: right;
  flex-grow: 0;
  flex-shrink: 0;
  flex-basis: calc(3 * var(--report-font-size));
}

**Comment by naodya** [comment]
@vaibbhav thanks for sharing this. I've added your fix and published version 2.8.0.
